#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
_count=1
while [ "$_count" -lt 21 ]; do
	echo $_count
	case $_count in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((_count++))
done
